# Generated by Django 5.2.8 on 2025-11-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
